# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Make Tar File
        run: tar -cpvzf ./$GITHUB_SHA.tgz *
        shell : bash

#       - name: Configure AWS Credentials
#         uses: aws-actions/configure-aws-credentials@v1
#         with:
#           aws-access-key-id: ${{secrets.AWS_ACCESS_KET_ID}}
#           aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
#           aws-region: ap-northeast-2

      - name: Upload to S3
        env: 
          AWS-ACCESS-KEY-ID: ${{secrets.AWS_ACCESS_KET_ID}}
          AWS-SECRET-ACCESS-KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        run: |
          aws s3 cp \
            --region ap-northeast-2 \
            ./$GITHUB_SHA.tgz s3://memorial-myslackbot/build/$GITHUB_SHA.tgz

      - name: Code deploy
        run: aws code create-deployment --application-name cicd-app \ 
              --file-exits-behavior OVERWRITE \ 
              --deployment-config-name CodeDeployDefault.OneAtATime \ 
              --deployment-group-name cicd-group \ 
              --s3-location bucket=memorial-myslackbot,bundleType=tgz, key=build/$GITHUB_SHA.tgz
